### ISSUE TITLE
Exchange explict count assertions with more flexible active record collection counts

### ISSUE THREAD

**Issue by kasugaijin** [kasugaijin/baja-pet-rescue#104]
The test suite is starting to exhibit brittleness due to assertions that expect an explicit count e.g., 3 of a given element. This means if you add another fixture, these tests break because the count has increase by one. Such assertions should be replaced with active record queries that count a collection. Therefore if you add one more record in the fixtures, it will be included in this count and the test won't break for this reason. 

This ticket is to focus on the explicit count assertions in `test/integration/adopter_applications_page_test.rb`

Acceptance criteria:
- explicit counts exchanged with active record queries that count a collection
- tests pass if a new record is added in the fixtures
- all tests pass

**Comment by Overlandcoder** [comment]
I'd love to work on this!

**Comment by kasugaijin** [comment]
All yours.

**Comment by kasugaijin** [comment]
closed by https://github.com/kasugaijin/baja-pet-rescue/pull/126
