### ISSUE TITLE
Streamline local setup process in README

### ISSUE THREAD

**Issue by JoshDevHub** [kasugaijin/baja-pet-rescue#116]
First off, this is a lovely project :dog: 

When cloning this I noticed a couple of steps in the [local environment setup](https://github.com/kasugaijin/baja-pet-rescue#local-setup) could be streamlined some.
- When a user does `ruby -v`, this is going to show the ruby version they currently have globally set. This project's `.ruby-version` file will automatically tell rbenv (or rvm) to use the required version of Ruby when the user is in this project. This means that devs don't necessarily have to have their global version set to 3.1.1, they just have to have that version installed and available for their version management tool to use. With rbenv, this means running `rbenv versions` and checking that 3.1.1 is in the list, and with rvm, running `rvm list rubies` and checking for the same.
- These [three commands here](https://github.com/kasugaijin/baja-pet-rescue/blob/main/README.md?plain=1#L114-L116) can all be run together with just a `rails db:setup`

Would love to make a PR if that all seems fine with you.

**Comment by kasugaijin** [comment]
Yes, please do! Thank you for catching this and reporting the issue. It sounds like a good change.

**Comment by kasugaijin** [comment]
Also, for my curiosity, how did you find this repo? I am happy you did.

**Comment by JoshDevHub** [comment]
> Also @JoshDevHub, for my curiosity, how did you find this repo? I am happy you did.

I watched the code review you had with Jason Swett, and I thought it looked like a really interesting project. It was easy to find with a little searching.
