### ISSUE TITLE
Navbar - switch positions of Donate and Successes

### ISSUE THREAD

**Issue by kasugaijin** [kasugaijin/baja-pet-rescue#142]
When I look at the Navbar, the Donate link should be where Successes link is and vice versa.

**Comment by RaspberryRat** [comment]
I'd be interested in this one. Would be my first open source contribution.

**Comment by kasugaijin** [comment]
Awesome! It's all yours. If you have any questions let me know on Discord.

**Comment by kasugaijin** [comment]
closed by https://github.com/kasugaijin/baja-pet-rescue/pull/147
