### ISSUE TITLE
Use newer version of bundler?

### ISSUE THREAD

**Issue by Overlandcoder** [kasugaijin/baja-pet-rescue#164]
When running `rake traceroute`, `rails test` or `rails test:all`, I always get this warning:

```Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.```

I remember looking into a fix for this back in January when I first started working on this app, and the solution is to basically use a newer version of bundler than the one that this app is using. I remember running `bundle update --bundler` on my cloned repo, and that fixed it.

When I wanted to push my updated Gemfile.lock today, I realized that my cloned repo's Gemfile.lock is using newer versions of many gems than this original repo's Gemfile.lock. So instead of pushing that file with all the newer versions of the gems, I wanted to keep it simple, and keep things in line with this repo's gem versions. I copy pasted this original repo's Gemfile.lock contents into my Gemfile.lock and ran `bundle install` to add the Traceroute gem. Then I ran `rails test:all`, and noticed that the old spell_checker warning was back again, because the bundler version got reverted back to the older one that this original repo is using.

That's a long-winded explanation, but I thought the context might be helpful. Basically, if you also get this spell_checker error/warning, we could fix it pretty easily by using a newer version of bundler by running `bundle update --bundler`. Would love to know what you think!

**Comment by kasugaijin** [comment]
Ah yes I do get that error and I tried updating bundler and it fixed the issue. Thank you. 
You could try making a PR with your gemfile.lock and we can see how the tests do in the pipeline and I can clone and see how it does on my machine. I don't suspect version upgrades will cause issues (fingers crossed). 
One caveat, for now let's keep it at Ruby  3.1.1 as I got an error when I tried updating to 3.1.2 not long ago. That's a task to address in the future.

**Comment by Overlandcoder** [comment]
> Ah yes I do get that error and I tried updating bundler and it fixed the issue. Thank you. You could try making a PR with your gemfile.lock and we can see how the tests do in the pipeline and I can clone and see how it does on my machine. I don't suspect version upgrades will cause issues (fingers crossed). One caveat, for now let's keep it at Ruby 3.1.1 as I got an error when I tried updating to 3.1.2 not long ago. That's a task to address in the future.

Sounds good! I made a PR, but honestly we can even ditch this update for now if you think it could cause any potential problems down the line. Totally up to you.

**Comment by kasugaijin** [comment]
Let's live dangerously :smile: 
I don't think it will be an issue. :crossed_fingers:
