### ISSUE TITLE
Possible dead code in app/services?

### ISSUE THREAD

**Issue by egemen-dev** [kasugaijin/baja-pet-rescue#165]
While working on service object https://github.com/kasugaijin/baja-pet-rescue/pull/160 I noticed that there might be a possible dead code in `app/services/geocode_backfilled_location.rb` the class `GeocodeBackfilledLocation` itself is not used anywhere, I wonder are you keeping this code for future use or it's forgotten?

**Comment by kasugaijin** [comment]
Yes this should really live in a rake task as it is a database related task that I executed when I refactored the locations data to create data for google maps. I decoupled location data from adopter profile data, and ran that task to generate coordinates. This ticket could be to move that logic to a rake task instead that can be called from the console.

**Comment by egemen-dev** [comment]
Yes. You can assign it to me and I will open a PR to remove it. @kasugaijin

**Comment by kasugaijin** [comment]
Assigned @egemen-dev
