### ISSUE TITLE
Add charts to active admin dashboard

### ISSUE THREAD

**Issue by kasugaijin** [kasugaijin/baja-pet-rescue#168]
It would be awesome to visualize some data from this application in active admin dashboard, such as adoptions, user sign ups and donations over time. This would be great practice at creating a dashboard in a rails application, and would be helpful for the site admin to see.

**Comment by egemen-dev** [comment]
I'm down to collab. We can achieve striking results using the [chartkick](https://chartkick.com). What do you think? @kasugaijin

**Comment by kasugaijin** [comment]
Yes chartkick looks like a great solution.
