### ISSUE TITLE
Stale branches

### ISSUE THREAD

**Issue by egemen-dev** [kasugaijin/baja-pet-rescue#173]
When you enter `git branch -r` on terminal, there are many stale branches coming up. It's making it harder to switch between branches. I think it's better to delete old branches after the merge. That way we can maintain and keep track of the branches easily. What do you think about it @kasugaijin?

**Comment by kasugaijin** [comment]
Yes this would be good housekeeping! Please go ahead and make a PR to remove branches that are not currently active.

**Comment by egemen-dev** [comment]
As you are the repo owner, you need to delete the branches. I have no permission to delete a branch :)

**Comment by kasugaijin** [comment]
Right...that's true. I will do that, and look to set branches to delete automatically after a PR is merged.
