### ISSUE TITLE
Tests for User Account Settings Page

### ISSUE THREAD

**Issue by kasugaijin** [kasugaijin/baja-pet-rescue#43]
`test/integration/user_account_test.rb`
This file tests the `/users/edit` route (Dashboard > Account Settings in UI) and could do with some additional tests to ensure the form is working as intended to edit user settings.

Acceptance Criteria
- Integration tests are added to the above file, and pass
- Tests check the form functionality works for setting a new password, setting a new first and last name.

**Comment by Eduardo06sp** [comment]
I would like to be assigned to this please!

**Comment by kasugaijin** [comment]
Done!
