### ISSUE TITLE
Tests for Contact Form

### ISSUE THREAD

**Issue by kasugaijin** [kasugaijin/baja-pet-rescue#44]
`/contacts/new`
Create a new integration test file `contact_form_test.rb` in `test/integration` and check that the form errors are displaying as expected. Note that the UI also makes use of `required` in the HTML, so you will see the default browser errors if you try to replicate the errors in the UI. Therefore, you can temporarily remove `required` in that form's view file and then submit the form to see the Rails error messages based on the model validation. 

Acceptance Criteria
- a new file `contact_form_test.rb` in the correct folder `test/integration`
- tests checking presence of errors for missing name, email and message fields

**Comment by Eduardo06sp** [comment]
I would love to take this!

**Comment by kasugaijin** [comment]
Done!

**Comment by kasugaijin** [comment]
Completed!
