### ISSUE TITLE
Remove applications with one click after an adoption is made

### ISSUE THREAD

**Issue by kasugaijin** [kasugaijin/baja-pet-rescue#58]
When an adoption is made, the status of 'adoption made' for that dog shows on each adopter user's applications page. The user then needs to make two clicks to withdraw and remove this application to get rid of it. The same applies for the successful adopter.

This can be improved. It would be better, if after an adoption is made, there is a single click to remove the application from the applications page. 

This ticket is to investigate the best way to implement this logic.

**Comment by Overlandcoder** [comment]
I'd love to take care of this!

**Comment by Overlandcoder** [comment]
By the way, what I noticed just now is that for the **successful adopter** to remove the application takes only 1 click.

**Comment by kasugaijin** [comment]
You know what. I just checked this out and it is a single click on the `Remove` button for any applicant. I think this ticket is a non-issue. Perhaps you can try and confirm that, too. If so, I will close it!

**Comment by Overlandcoder** [comment]
> You know what? I just checked this out and it is a single click on the `Remove` button for any applicant. I think this ticket is a non-issue. Perhaps you can try and confirm that, too. If so, I will close it!

I tested it out for all types of applicants now, and it indeed requires just a single click to remove the application

**Comment by kasugaijin** [comment]
Closed! Thank you for checking.
