### ISSUE TITLE
Test an email is sent when a user goes through the Forgot Password flow

### ISSUE THREAD

**Issue by kasugaijin** [kasugaijin/baja-pet-rescue#81]
We are missing a test in `user_account_test.rb` for the forgot password flow. This issue is to create that test, making sure the user receives an email. See the examples of using ActionMailer in this file if necessary. 

Acceptance Criteria: 
- test checking email is sent when user goes through Forgot Password flow
- all tests pass

**Comment by Overlandcoder** [comment]
I'd love to take care of this!

**Comment by kasugaijin** [comment]
All yours!
