### ISSUE TITLE
A couple possible improvements for '/adopter_profile/new'

### ISSUE THREAD

**Issue by Overlandcoder** [kasugaijin/baja-pet-rescue#82]
For '/adopter_profile/new':

- It might be better to rename 'Week day' to 'Weekday'
- I use Firefox in my VM while working on this app, and I noticed that all of the 'Yes/No' radio buttons are not aligned properly. @kasugaijin I can send you a screenshot in Discord to illustrate what I mean. I tried it out in Chrome, and there are no alignment issues there

**Comment by kasugaijin** [comment]
Oh yes please send a screenshot!

**Comment by Eduardo06sp** [comment]
For the sake of manually testing: that page renders perfectly fine for me

The page where it asks you a bunch of questions right after registering as an adopter.
It contains the following text at the top:
> The following questions help us learn more about you so we can match you with the right pooch.

**Firefox versions tested:**
110.0b5 (Latest dev)
108.0.2 (Latest stable)

**OS:** Pop!_OS 22.04 (it's based on Ubuntu)

**Comment by kasugaijin** [comment]
Thank you for testing and reporting back @Eduardo06sp. 
@Overlandcoder you stated this was also working for you as expected now?
If so I will close this issue; please confirm.

**Comment by Overlandcoder** [comment]
> Thank you for testing and reporting back @Eduardo06sp. @Overlandcoder you stated this was also working for you as expected now? If so I will close this issue; please confirm.

Yep I tested it multiple times on multiple new accounts, and it seems to be working fine.

**Comment by kasugaijin** [comment]
Ok. Case closed!
