### ISSUE TITLE
Tests for the custom errors controller

### ISSUE THREAD

**Issue by kasugaijin** [kasugaijin/baja-pet-rescue#85]
The application has custom error responses for when a 404, 500 or 422 hits the routes file (see `match` verbs). These are sent to the `errors_controller.rb` to render the appropriate view. These are not tested. 

This issue is to re-create a request that will cause each of the three errors to be produced and assert that the expected content is displayed i.e., the error code and message. 

Acceptance criteria:
- test for each of the three error codes asserting expected view file is rendered
- all tests pass

**Comment by Overlandcoder** [comment]
I'd love to write these tests

**Comment by kasugaijin** [comment]
All yours!

**Comment by kasugaijin** [comment]
Closed by https://github.com/kasugaijin/baja-pet-rescue/pull/101
