### ISSUE TITLE
Test user gets redirected to root page on sign in/sign out

### ISSUE THREAD

**Issue by kasugaijin** [kasugaijin/baja-pet-rescue#87]
`user_account_test.rb'

Acceptance criteria:
- a test to show a user gets redirected to the root path on sign in, and again on sign out
- tests pass

**Comment by Eduardo06sp** [comment]
I would like to take this!

**Comment by kasugaijin** [comment]
All yours!

**Comment by kasugaijin** [comment]
Closed by https://github.com/kasugaijin/baja-pet-rescue/pull/93
