### ISSUE TITLE
Test adopted dogs can't be shown as an adoptable dog

### ISSUE THREAD

**Issue by kasugaijin** [kasugaijin/baja-pet-rescue#89]
`adoptable_dogs_controller.rb` show action will take a user to `/adoptable_dogs/:id` unless the dog is adopted. In that case the user is redirected with a flash. 

Acceptance criteria:
- test shows that trying to access show action in adoptable_dogs controller using an id of an adopted dog causes a redirect with flash. 
- all tests pass.
- add the test to `adoptable_dog_show_test.rb`

**Comment by Overlandcoder** [comment]
I'd love to tackle this next!

**Comment by kasugaijin** [comment]
Close by https://github.com/kasugaijin/baja-pet-rescue/pull/105
